#!/usr/bin/env bash

# Copyright (c) 2026 Tabith LLC.
# Use of this source code is governed by the Business Source License 1.1
# included in the LICENSE file at the root of this repository. As of the
# Change Date listed there, the work is available under MPL 2.0.
# SPDX-License-Identifier: BUSL-1.1

# Regenerate (or --check) the pinned host-requirements files from uv.lock.
#
# The installers feed venya-{core,executor}-requirements.txt to `uv pip install`.
# Keeping them as `uv export` output pins every transitive dependency to the
# locked version, so a deployed fleet runs the bytes that were tested instead of
# resolving latest-at-install-time (ticket installer-deps-not-lock-pinned).
# Local workspace packages are emitted non-editable (./packages/...) to preserve
# the site-packages deploy model the server's static files rely on.
#
# Usage:
#   scripts/pin-requirements.sh          # regenerate both files
#   scripts/pin-requirements.sh --check  # exit non-zero if they drifted from uv.lock
set -euo pipefail
cd "$(dirname "$0")/.."

# Single source for the export command. Regen and --check MUST use identical
# flags or the autogenerated header comment would never match byte-for-byte.
export_for() {
    uv export --frozen --no-emit-project --no-editable --no-hashes --no-dev \
        --format requirements-txt "$@"
}

# Per-target scoping keeps each install minimal (core does not pull executor's
# deps and vice versa) — matters for the offline mirror footprint.
CORE_PKGS=(--package core --package server --package venya-cli)
EXEC_PKGS=(--package core --package executor --package venya-cli)

if [[ "${1:-}" == "--check" ]]; then
    fail=0
    if ! export_for "${CORE_PKGS[@]}" | diff -u venya-core-requirements.txt -; then
        echo "ERROR: venya-core-requirements.txt drifted from uv.lock — run scripts/pin-requirements.sh and commit." >&2
        fail=1
    fi
    if ! export_for "${EXEC_PKGS[@]}" | diff -u venya-executor-requirements.txt -; then
        echo "ERROR: venya-executor-requirements.txt drifted from uv.lock — run scripts/pin-requirements.sh and commit." >&2
        fail=1
    fi
    if [[ "$fail" -eq 0 ]]; then
        echo "pinned requirements match uv.lock"
    fi
    exit "$fail"
fi

export_for "${CORE_PKGS[@]}" > venya-core-requirements.txt
export_for "${EXEC_PKGS[@]}" > venya-executor-requirements.txt
echo "regenerated venya-core-requirements.txt + venya-executor-requirements.txt from uv.lock"
